#!/bin/bash

# script to convert foo.tex to PDF
# usage: ./run foo.tex  or ./run foo
# above generates foo.pdf and other files

# remove filename extension from arg
file="${1%.*}"

./clean
pdflatex "$file"
bibtex   "$file"
pdflatex "$file"
pdflatex "$file"
pdflatex "$file"  # we sometimes need to run pdflatex 3 times

# in case you want to diff your changes visually
diff-pdf --view "$file".pdf ../doc/"$file".pdf

mv "$file".pdf ../doc

echo "--------------------------------------------------------------------------------"
grep Warning "$file".log

#./clean

# note: to diff 2 PDF files visually, type the following:
#   diff-pdf --view file1.pdf file2.pdf
# alternatively, use pdftotext to convert each PDF to text and then diff the text files:
#   pdftotext file1.pdf  # this generates file1.txt
#   pdftotext file2.pdf  # this generates file2.txt
#   diff file1.txt file2.txt
