#!/bin/bash

# script to convert foo.tex to PDF
# usage: ./run foo
# above generates foo.pdf and other files

./clean
pdflatex "$1"
bibtex   "$1"
pdflatex "$1"
pdflatex "$1"
pdflatex "$1"  # we sometimes need to run pdflatex 3 times

mv "$1".pdf ../doc

echo "--------------------------------------------------------------------------------"
grep Warning "$1".log

./clean

# note: to diff 2 PDF files visually, type the following:
#   diff-pdf --view file1.pdf file2.pdf
# alternatively, use pdftotext to convert each PDF to text and then diff the text files:
#   pdftotext file1.pdf  # this generates file1.txt
#   pdftotext file2.pdf  # this generates file2.txt
#   diff file1.txt file2.txt
