#!/bin/bash

# script to submit foo.tex to arXiv
# usage: ./submit foo.tex
# above generates a directory foo_submit and a tar gz file foo_submit.tar.gz
# only upload this tar file to arXiv and see the notes in README on how to submit

# note: to double-check if everything works, run pdflatex foo two times
# (or sometimes three times) as follows:
#  cd foo_submit
#  pdflatex foo && pdflatex foo

# remove filename extension from arg
file="${1%.*}"

DIR="$file"_submit

rm -Rf "$DIR" "$DIR".tar.gz
mkdir "$DIR"

./run "$file"

cp *.sty references.bib "$file".bbl "$file".tex "$DIR"
cp ../doc/fig/"$file"_fig*.pdf "$DIR"

# modify the figure-paths in the tex file: ../doc/fig/ -> ./
sed -i "" "s,../doc/fig/,./,g" "$DIR"/"$file".tex
# the two quotes (empty string) at the beginning of sed are for running on mac

# TODO: it might also work without the sed command, but only if the tar.gz
# archive is flat and has only one directory to the tex file (right now the
# archive includes the directory 'foo_submit')

tar -czvf "$DIR".tar.gz "$DIR"
