#!/bin/bash

# script to submit foo.tex to arXiv
# usage: ./submit foo.tex
# above generates a directory foo_submit and a tar gz file foo_submit.tar.gz
# only upload this tar file to arXiv and see the notes in README on how to submit

# note: to double-check if everything works, run pdflatex foo two times
# (or sometimes three times) as follows:
#  cd foo_submit
#  pdflatex foo && pdflatex foo

# remove filename extension from arg
file="${1%.*}"

DIR="$file"_submit

rm -Rf "$DIR" "$DIR".tar.gz
mkdir "$DIR"
mkdir -p "$DIR"/tex "$DIR"/doc/fig

./run "$file"

cp arxiv.sty references.bib "$file".bbl "$file".tex "$DIR"/tex
cp ../doc/fig/"$file"_fig* "$DIR"/doc/fig

tar -czvf "$DIR".tar.gz "$DIR"
