#!/bin/bash

# script to submit foo.tex to arXiv
# usage: ./submit foo
# above generates a directory foo_submit and a tar gz file foo_submit.tar.gz
# only upload this tar file to arXiv and see the notes in README on how to submit

# note: to double-check if everything works, run pdflatex foo two times
# (or sometimes three times) as follows:
#  cd foo_submit
#  pdflatex foo && pdflatex foo

DIR="$1"_submit

rm -Rf "$DIR" "$DIR".tar.gz
mkdir  "$DIR"

./run "$1"

cp arxiv.sty references.bib "$1".bbl "$1".tex figs/"$1"_fig* "$DIR"

tar -czvf "$DIR".tar.gz "$DIR"
